In [17]:
import pandas as pd

TICKERS_EU = [ "KRZ.IR", "A5G.IR", "BIRG.IR", "ASML.AS", "SAP.DE", "MC.PA", "NOVO-B.CO", "SIE.DE", "OR.PA", "NESN.SW",]
TICKERS = ["TSLA", "AMZN", "NIO", "MSFT", "AAPL", "GOOG", "NFLX", "COIN"]
output_path="/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent"

region = "us"
system = "workflow"
reflection = "false"

all_system_summary = f"{output_path}/results/validation/{region}/table1_{region}_summary.csv"
each_system_rows = f"{output_path}/results/validation/{region}/table2_{region}_rows_{system}_{reflection}.csv"
one_system_summary = f"{output_path}/results/validation/{region}/table2_{region}_summary_{system}_{reflection}.csv"

US STOCKS ["TSLA", "AMZN", "NIO", "MSFT", "AAPL", "GOOG", "NFLX", "COIN"]

In [18]:
all_sys_sum = pd.read_csv(all_system_summary)
# all_sys_sum.head()
all_sys_sum

,model,architecture,reflection,n_analyses,n_runs,n_buy,n_hold,n_sell,mean_nmae,mean_penalty_rate,mean_score_one,mean_score,mean_tokens_per_analysis,mean_total_tokens
0,gpt-5-mini,workflow,False,28,1,14,0,14,0.064603,0.0,0.064603,0.064603,83335.214286,83335.214286

In [19]:
one_sys_sum1 = pd.read_csv(one_system_summary)
# one_sys_sum1.head()
one_sys_sum1

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,NetRevenue_TTM,2,2,2,1,0.000649,0.000649,0.000649,0.004201,0.0,0.000649,10.0,1,2026-02-25,2026-02-25,NaN
1,EBIT_TTM,2,2,2,1,0.004999,0.004999,0.004999,0.076623,0.0,0.004999,10.0,1,2026-02-25,2026-02-25,NaN
2,NetProfit_TTM,2,2,2,1,0.010193,0.010193,0.010193,0.140038,0.0,0.010193,10.0,1,2026-02-25,2026-02-25,NaN
3,GrossMargin,2,2,2,1,0.015390,0.015390,0.015390,0.030025,0.0,0.015390,10.0,1,2026-02-25,2026-02-25,NaN
4,EV_EBIT,2,2,2,1,0.027740,0.027740,0.027740,0.068961,0.0,0.027740,10.0,1,2026-02-25,2026-02-25,NaN
5,EPS,2,2,2,1,0.037986,0.037986,0.037986,0.142384,0.0,0.037986,10.0,1,2026-02-25,2026-02-25,NaN
6,CurrentRatio,2,2,2,1,0.044517,0.044517,0.044517,0.022127,0.0,0.044517,10.0,1,2026-02-25,2026-02-25,NaN
7,EBITMargin,2,2,2,1,0.068756,0.068756,0.068756,0.081743,0.0,0.068756,10.0,1,2026-02-25,2026-02-25,NaN
8,PriceToSales,2,2,2,1,0.078230,0.078230,0.078230,0.091464,0.0,0.078230,10.0,1,2026-02-25,2026-02-25,NaN
9,EV_EBITDA,2,2,2,1,0.083606,0.083606,0.083606,0.115486,0.0,0.083606,10.0,1,2026-02-25,2026-02-25,NaN
10,NetMargin,2,2,2,1,0.142273,0.142273,0.142273,0.137198,0.0,0.142273,10.0,1,2026-02-25,2026-02-25,NaN
11,ROIC,2,2,2,1,0.252706,0.252706,0.252706,0.283781,0.0,0.252706,10.0,1,2026-02-25,2026-02-25,NaN
12,NetDebt,2,2,2,1,0.295789,0.295789,0.295789,0.200070,0.0,0.295789,10.0,1,2026-02-25,2026-02-25,NaN
13,P_E,2,2,2,1,0.297927,0.297927,0.297927,0.295189,0.0,0.297927,10.0,1,2026-02-25,2026-02-25,NaN
14,GrossDebt,2,2,2,1,0.320891,0.320891,0.320891,0.477931,0.0,0.320891,10.0,1,2026-02-25,2026-02-25,NaN
15,CashAndEquivalents,2,2,2,1,0.376978,0.376978,0.376978,0.448965,0.0,0.376978,10.0,1,2026-02-25,2026-02-25,NaN
16,P_B,2,2,2,1,0.410884,0.410884,0.410884,0.465735,0.0,0.410884,10.0,1,2026-02-25,2026-02-25,NaN
17,ShareholdersEquity,2,2,2,1,0.480944,0.480944,0.480944,0.895935,0.0,0.480944,10.0,1,2026-02-25,2026-02-25,NaN
18,ROE,2,2,2,1,0.643304,0.643304,0.643304,0.587125,0.0,0.643304,10.0,1,2026-02-25,2026-02-25,NaN
19,GrossDebt_Equity,2,2,2,1,0.683154,0.683154,0.683154,0.482980,0.0,0.683154,10.0,1,2026-02-25,2026-02-25,NaN
20,BVPS,2,2,2,1,1.064109,1.064109,1.064109,0.738385,0.0,1.064109,10.0,1,2026-02-25,2026-02-25,NaN

In [20]:
sys1 = pd.read_csv(each_system_rows)
# sys1.head()
sys1

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,input_tokens,output_tokens,total_tokens,requests,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,AMZN,2026-02-25,0,BVPS,3.830631e+01,2.352000e+01,gold,2026-02-25,2026-02-25,USD_per_share,...,64641,4519,69160,2,1.267036,0.628670,minmax_gold,0,1.185000e+01,2.352000e+01
1,AMZN,2026-02-25,0,CashAndEquivalents,8.681000e+10,1.230300e+11,gold,2026-02-25,2026-02-25,USD,...,64641,4519,69160,2,0.445072,0.294400,minmax_gold,0,4.165000e+10,1.230300e+11
2,AMZN,2026-02-25,0,CurrentRatio,1.050815e+00,1.050000e+00,gold,2026-02-25,2026-02-25,multiple,...,64641,4519,69160,2,0.000799,0.000777,minmax_gold,0,1.050000e+00,2.070000e+00
3,AMZN,2026-02-25,0,EBITMargin,1.115530e+01,1.116000e+01,gold,2026-02-25,2026-02-25,percent,...,64641,4519,69160,2,0.000775,0.000421,minmax_gold,0,5.090000e+00,1.116000e+01
4,AMZN,2026-02-25,0,EBIT_TTM,7.997500e+10,7.998000e+10,gold,2026-02-25,2026-02-25,USD,...,64641,4519,69160,2,0.000067,0.000063,minmax_gold,0,4.870000e+09,7.998000e+10
5,AMZN,2026-02-25,0,EPS,7.170000e+00,7.170000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,64641,4519,69160,2,0.000000,0.000000,minmax_gold,0,1.510000e+00,7.170000e+00
6,AMZN,2026-02-25,0,EV_EBIT,2.804450e+01,3.113000e+01,gold,2026-02-25,2026-02-25,multiple,...,64641,4519,69160,2,0.011983,0.099117,minmax_gold,0,3.113000e+01,2.886200e+02
7,AMZN,2026-02-25,0,EV_EBITDA,1.539040e+01,1.708000e+01,gold,2026-02-25,2026-02-25,multiple,...,64641,4519,69160,2,0.015060,0.098923,minmax_gold,0,1.708000e+01,1.292700e+02
8,AMZN,2026-02-25,0,GrossDebt,6.929100e+10,1.529900e+11,gold,2026-02-25,2026-02-25,USD,...,64641,4519,69160,2,0.601286,0.547088,minmax_gold,0,1.379000e+10,1.529900e+11
9,AMZN,2026-02-25,0,GrossDebt_Equity,1.685646e-01,3.722000e-01,gold,2026-02-25,2026-02-25,multiple,...,64641,4519,69160,2,1.011099,0.547113,minmax_gold,0,1.708000e-01,3.722000e-01
10,AMZN,2026-02-25,0,GrossMargin,5.028566e+01,5.029000e+01,gold,2026-02-25,2026-02-25,percent,...,64641,4519,69160,2,0.000130,0.000086,minmax_gold,0,1.701000e+01,5.029000e+01
11,AMZN,2026-02-25,0,NetDebt,-1.751900e+10,-2.116000e+10,gold,2026-02-25,2026-02-25,USD,...,64641,4519,69160,2,0.352469,0.172070,minmax_gold,0,-2.116000e+10,-1.083000e+10
12,AMZN,2026-02-25,0,NetMargin,1.083378e+01,1.083000e+01,gold,2026-02-25,2026-02-25,percent,...,64641,4519,69160,2,0.000711,0.000349,minmax_gold,0,5.510000e+00,1.083000e+01
13,AMZN,2026-02-25,0,NetProfit_TTM,7.767000e+10,7.767000e+10,gold,2026-02-25,2026-02-25,USD,...,64641,4519,69160,2,0.000000,0.000000,minmax_gold,0,5.270000e+09,7.767000e+10
14,AMZN,2026-02-25,0,NetRevenue_TTM,7.169240e+11,7.169200e+11,gold,2026-02-25,2026-02-25,USD,...,64641,4519,69160,2,0.000006,0.000006,minmax_gold,0,9.563000e+10,7.169200e+11
15,AMZN,2026-02-25,0,P_B,5.498833e+00,9.810000e+00,gold,2026-02-25,2026-02-25,multiple,...,64641,4519,69160,2,0.155582,0.439467,minmax_gold,0,9.810000e+00,3.752000e+01
16,AMZN,2026-02-25,0,P_E,2.937796e+01,3.167000e+01,gold,2026-02-25,2026-02-25,multiple,...,64641,4519,69160,2,0.009543,0.072372,minmax_gold,0,3.167000e+01,2.718500e+02
17,AMZN,2026-02-25,0,PriceToSales,3.152883e+00,3.430000e+00,gold,2026-02-25,2026-02-25,multiple,...,64641,4519,69160,2,0.023993,0.080792,minmax_gold,0,3.430000e+00,1.498000e+01
18,AMZN,2026-02-25,0,ROE,1.889482e+01,3.667000e+01,gold,2026-02-25,2026-02-25,percent,...,64641,4519,69160,2,0.815749,0.484734,minmax_gold,0,1.488000e+01,3.667000e+01
19,AMZN,2026-02-25,0,ROIC,1.633860e+01,1.317000e+01,gold,2026-02-25,2026-02-25,percent,...,64641,4519,69160,2,0.352851,0.240592,minmax_gold,0,4.190000e+00,1.317000e+01
20,AMZN,2026-02-25,0,ShareholdersEquity,4.110650e+11,2.506500e+11,gold,2026-02-25,2026-02-25,USD,...,64641,4519,69160,2,0.754965,0.639996,minmax_gold,0,3.817000e+10,2.506500e+11
21,TSLA,2026-02-25,0,BVPS,2.190000e+01,1.185000e+01,gold,2026-02-25,2026-02-25,USD_per_share,...,55620,6504,62124,2,0.861183,0.848101,minmax_gold,0,1.185000e+01,2.352000e+01
22,TSLA,2026-02-25,0,CashAndEquivalents,1.651300e+10,4.165000e+10,gold,2026-02-25,2026-02-25,USD,...,55620,6504,62124,2,0.308884,0.603529,minmax_gold,0,4.165000e+10,1.230300e+11
23,TSLA,2026-02-25,0,CurrentRatio,2.160000e+00,2.070000e+00,gold,2026-02-25,2026-02-25,multiple,...,55620,6504,62124,2,0.088235,0.043478,minmax_gold,0,1.050000e+00,2.070000e+00
24,TSLA,2026-02-25,0,EBITMargin,5.920000e+00,5.090000e+00,gold,2026-02-25,2026-02-25,percent,...,55620,6504,62124,2,0.136738,0.163065,minmax_gold,0,5.090000e+00,1.116000e+01
25,TSLA,2026-02-25,0,EBIT_TTM,5.616000e+09,4.870000e+09,gold,2026-02-25,2026-02-25,USD,...,55620,6504,62124,2,0.009932,0.153183,minmax_gold,0,4.870000e+09,7.998000e+10
26,TSLA,2026-02-25,0,EPS,1.080000e+00,1.510000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,55620,6504,62124,2,0.075972,0.284768,minmax_gold,0,1.510000e+00,7.170000e+00
27,TSLA,2026-02-25,0,EV_EBIT,2.774200e+02,2.886200e+02,gold,2026-02-25,2026-02-25,multiple,...,55620,6504,62124,2,0.043497,0.038805,minmax_gold,0,3.113000e+01,2.886200e+02
28,TSLA,2026-02-25,0,EV_EBITDA,1.463400e+02,1.292700e+02,gold,2026-02-25,2026-02-25,multiple,...,55620,6504,62124,2,0.152153,0.132049,minmax_gold,0,1.708000e+01,1.292700e+02
29,TSLA,2026-02-25,0,GrossDebt,8.153000e+09,1.379000e+10,gold,2026-02-25,2026-02-25,USD,...,55620,6504,62124,2,0.040496,0.408774,minmax_gold,0,1.379000e+10,1.529900e+11
30,TSLA,2026-02-25,0,GrossDebt_Equity,9.926099e-02,1.708000e-01,gold,2026-02-25,2026-02-25,multiple,...,55620,6504,62124,2,0.355209,0.418847,minmax_gold,0,1.708000e-01,3.722000e-01
31,TSLA,2026-02-25,0,GrossMargin,1.803000e+01,1.701000e+01,gold,2026-02-25,2026-02-25,percent,...,55620,6504,62124,2,0.030649,0.059965,minmax_gold,0,1.701000e+01,5.029000e+01
32,TSLA,2026-02-25,0,NetDebt,-8.360000e+09,-1.083000e+10,gold,2026-02-25,2026-02-25,USD,...,55620,6504,62124,2,0.239109,0.228070,minmax_gold,0,-2.116000e+10,-1.083000e+10
33,TSLA,2026-02-25,0,NetMargin,4.000000e+00,5.510000e+00,gold,2026-02-25,2026-02-25,percent,...,55620,6504,62124,2,0.283835,0.274047,minmax_gold,0,5.510000e+00,1.083000e+01
34,TSLA,2026-02-25,0,NetProfit_TTM,3.794000e+09,5.270000e+09,gold,2026-02-25,2026-02-25,USD,...,55620,6504,62124,2,0.020387,0.280076,minmax_gold,0,5.270000e+09,7.767000e+10
35,TSLA,2026-02-25,0,NetRevenue_TTM,9.482700e+10,9.563000e+10,gold,2026-02-25,2026-02-25,USD,...,55620,6504,62124,2,0.001292,0.008397,minmax_gold,0,9.563000e+10,7.169200e+11
36,TSLA,2026-02-25,0,P_B,1.906000e+01,3.752000e+01,gold,2026-02-25,2026-02-25,multiple,...,55620,6504,62124,2,0.666185,0.492004,minmax_gold,0,9.810000e+00,3.752000e+01
37,TSLA,2026-02-25,0,P_E,4.126700e+02,2.718500e+02,gold,2026-02-25,2026-02-25,multiple,...,55620,6504,62124,2,0.586310,0.518006,minmax_gold,0,3.167000e+01,2.718500e+02
38,TSLA,2026-02-25,0,PriceToSales,1.651000e+01,1.498000e+01,gold,2026-02-25,2026-02-25,multiple,...,55620,6504,62124,2,0.132468,0.102136,minmax_gold,0,3.430000e+00,1.498000e+01
39,TSLA,2026-02-25,0,ROE,4.620000e+00,1.488000e+01,gold,2026-02-25,2026-02-25,percent,...,55620,6504,62124,2,0.470858,0.689516,minmax_gold,0,1.488000e+01,3.667000e+01
40,TSLA,2026-02-25,0,ROIC,5.560000e+00,4.190000e+00,gold,2026-02-25,2026-02-25,percent,...,55620,6504,62124,2,0.152561,0.326969,minmax_gold,0,4.190000e+00,1.317000e+01
41,TSLA,2026-02-25,0,ShareholdersEquity,8.213700e+10,3.817000e+10,gold,2026-02-25,2026-02-25,USD,...,55620,6504,62124,2,0.206923,1.151873,minmax_gold,0,3.817000e+10,2.506500e+11

Dataset

In [6]:
split_2025 = pd.read_csv("/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent/data/processed/splits/test_2025-01-01_to_2026-02-25.csv")
split_2025.head()
mask = (split_2025["date"] == "2026-02-24") & (split_2025["ticker"] == "AAPL")
check = split_2025.loc[mask].iloc[0]
check

date                            2026-02-24
ticker                                AAPL
adj_close                       272.140015
ret_1d                            0.616995
log_ret_1d                        0.022144
Volume                           -0.127226
filed                           2026-01-30
Assets                             0.77603
Liabilities                       1.737268
StockholdersEquity               -0.144499
Revenues                               NaN
NetIncomeLoss                      0.99671
OperatingIncomeLoss               1.155145
EarningsPerShareBasic            -0.028904
CommonStockSharesOutstanding       1.43771
ret_5d                            0.350847
ret_20d                           0.328203
vol_20d                          -0.575568
vol_60d                          -0.992675
target_ret_1d                      0.00768
Name: 285, dtype: object

EU STOCKS

In [7]:
region = "eu"
system = "workflow"
reflection = "false"

all_system_summary_eu = f"{output_path}/results/validation/{region}/table1_{region}_summary.csv"
each_system_rows_eu = f"{output_path}/results/validation/{region}/table2_{region}_rows_{system}_{reflection}.csv"
one_system_summary_eu = f"{output_path}/results/validation/{region}/table2_{region}_summary_{system}_{reflection}.csv"

In [8]:
all_sys_sum_eu = pd.read_csv(all_system_summary_eu)
# all_sys_sum_eu.head()
all_sys_sum_eu

,model,architecture,reflection,n_analyses,n_runs,n_buy,n_hold,n_sell,mean_nmae,mean_penalty_rate,mean_score_one,mean_score,mean_tokens_per_analysis,mean_total_tokens
0,gpt-5-mini,workflow,False,14,1,8,5,1,0.073624,0.0,0.073624,0.073624,16022.571429,16022.571429

In [9]:
one_sys_sum_eu = pd.read_csv(one_system_summary_eu)
# one_sys_sum_eu.head()
one_sys_sum_eu

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,GrossDebt,1,1,1,1,0.003333,0.003333,0.003333,0.003333,0.0,0.003333,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
1,GrossMargin,1,1,1,1,0.005410,0.005410,0.005410,0.005410,0.0,0.005410,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
2,EBITMargin,1,1,1,1,0.027911,0.027911,0.027911,0.027911,0.0,0.027911,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
3,GrossDebt_Equity,1,1,1,1,0.029998,0.029998,0.029998,0.029998,0.0,0.029998,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
4,CurrentRatio,1,1,1,1,0.036797,0.036797,0.036797,0.036797,0.0,0.036797,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
5,NetMargin,1,1,1,1,0.044483,0.044483,0.044483,0.044483,0.0,0.044483,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
6,NetProfit_TTM,1,1,1,1,0.153137,0.153137,0.153137,0.153137,0.0,0.153137,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
7,EBIT_TTM,1,1,1,1,0.173026,0.173026,0.173026,0.173026,0.0,0.173026,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
8,EPS,1,1,1,1,0.173184,0.173184,0.173184,0.173184,0.0,0.173184,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
9,ROIC,1,1,1,1,0.184238,0.184238,0.184238,0.184238,0.0,0.184238,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
10,NetRevenue_TTM,1,1,1,1,0.206843,0.206843,0.206843,0.206843,0.0,0.206843,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
11,PriceToSales,1,1,1,1,0.212259,0.212259,0.212259,0.212259,0.0,0.212259,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
12,EV_EBIT,1,1,1,1,0.229535,0.229535,0.229535,0.229535,0.0,0.229535,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
13,EV_EBITDA,1,1,1,1,0.255399,0.255399,0.255399,0.255399,0.0,0.255399,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
14,P_E,1,1,1,1,0.262715,0.262715,0.262715,0.262715,0.0,0.262715,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
15,CashAndEquivalents,1,1,1,1,1.517739,1.517739,1.517739,1.517739,0.0,1.517739,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
16,NetDebt,1,1,1,1,3.217769,3.217769,3.217769,3.217769,0.0,3.217769,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback

In [10]:
sys_eu = pd.read_csv(each_system_rows_eu)
# sys_eu.head()
sys_eu

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,input_tokens,output_tokens,total_tokens,requests,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,ASML.AS,2026-02-26,0,CashAndEquivalents,1.291600e+10,5.130000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,1.517739,1.517739,ape_fallback_zero_range,0,5.130000e+09,5.130000e+09
1,ASML.AS,2026-02-26,0,CurrentRatio,1.261796e+00,1.310000e+00,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.036797,0.036797,ape_fallback_zero_range,0,1.310000e+00,1.310000e+00
2,ASML.AS,2026-02-26,0,EBITMargin,3.530628e+01,3.632000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.027911,0.027911,ape_fallback_zero_range,0,3.632000e+01,3.632000e+01
3,ASML.AS,2026-02-26,0,EBIT_TTM,1.372440e+10,1.170000e+10,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.173026,0.173026,ape_fallback_zero_range,0,1.170000e+10,1.170000e+10
4,ASML.AS,2026-02-26,0,EPS,2.940000e+01,2.506000e+01,gold,2026-02-26,2026-02-26,USD_per_share,...,10538,6552,17090,2,0.173184,0.173184,ape_fallback_zero_range,0,2.506000e+01,2.506000e+01
5,ASML.AS,2026-02-26,0,EV_EBIT,3.393516e+01,2.760000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.229535,0.229535,ape_fallback_zero_range,0,2.760000e+01,2.760000e+01
6,ASML.AS,2026-02-26,0,EV_EBITDA,3.158585e+01,2.516000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.255399,0.255399,ape_fallback_zero_range,0,2.516000e+01,2.516000e+01
7,ASML.AS,2026-02-26,0,GrossDebt,2.709000e+09,2.700000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.003333,0.003333,ape_fallback_zero_range,0,2.700000e+09,2.700000e+09
8,ASML.AS,2026-02-26,0,GrossDebt_Equity,1.381283e-01,1.424000e-01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.029998,0.029998,ape_fallback_zero_range,0,1.424000e-01,1.424000e-01
9,ASML.AS,2026-02-26,0,GrossMargin,5.215629e+01,5.244000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.005410,0.005410,ape_fallback_zero_range,0,5.244000e+01,5.244000e+01
10,ASML.AS,2026-02-26,0,NetDebt,-1.020700e+10,-2.420000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,3.217769,3.217769,ape_fallback_zero_range,0,-2.420000e+09,-2.420000e+09
11,ASML.AS,2026-02-26,0,NetMargin,2.921970e+01,3.058000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.044483,0.044483,ape_fallback_zero_range,0,3.058000e+01,3.058000e+01
12,ASML.AS,2026-02-26,0,NetProfit_TTM,1.135840e+10,9.850000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.153137,0.153137,ape_fallback_zero_range,0,9.850000e+09,9.850000e+09
13,ASML.AS,2026-02-26,0,NetRevenue_TTM,3.887240e+10,3.221000e+10,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.206843,0.206843,ape_fallback_zero_range,0,3.221000e+10,3.221000e+10
14,ASML.AS,2026-02-26,0,P_E,4.170748e+01,3.303000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.262715,0.262715,ape_fallback_zero_range,0,3.303000e+01,3.303000e+01
15,ASML.AS,2026-02-26,0,PriceToSales,1.224382e+01,1.010000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.212259,0.212259,ape_fallback_zero_range,0,1.010000e+01,1.010000e+01
16,ASML.AS,2026-02-26,0,ROIC,3.648088e+01,4.472000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.184238,0.184238,ape_fallback_zero_range,0,4.472000e+01,4.472000e+01

In [11]:
# split_2025_eu = pd.read_csv("/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent/data_eu/processed/splits/test_2025-01-01_to_2026-02-26.csv")
# # split_2025_eu.head()
# mask_eu = (split_2025["date"] == "2026-02-24") & (split_2025["ticker"] == "ASML.AS")
# check_eu = split_2025.loc[mask].iloc[0]
# check_eu