In [1]:
# At (Pdb) prompt:
# n next line
# s step into
# c continue
# p args / pp requested_tickers inspect vars
# l show code
# q quit
# Workflow mode
# %run -d -b 113 -b 118 -b 184 -b 195 run_one_ticker.py -- --ticker TSLA --mode workflow --model gpt-5-mini --n-times 1 --max-turns 30
# Agent mode (with MCP)
# %run -d -b 113 -b 118 -b 177 -b 186 -b 195 run_one_ticker.py -- --ticker TSLA --mode agent --model gpt-5-mini --mcp --n-times 1 --max-turns 30

In [2]:
import pandas as pd

TICKERS_EU = [ "KRZ.IR", "A5G.IR", "BIRG.IR", "ASML.AS", "SAP.DE", "MC.PA", "NOVO-B.CO", "SIE.DE", "OR.PA", "NESN.SW",]
TICKERS = ["TSLA", "AMZN", "NIO", "MSFT", "AAPL", "GOOG", "NFLX", "COIN"]
output_path="/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent"

region = "us"
system = "workflow"
reflection = "false"

all_system_summary = f"{output_path}/results/validation/{region}/table1_{region}_summary.csv"
each_system_rows = f"{output_path}/results/validation/{region}/table2_{region}_rows_{system}_{reflection}.csv"
one_system_summary = f"{output_path}/results/validation/{region}/table2_{region}_summary_{system}_{reflection}.csv"

US STOCKS ["TSLA", "AMZN", "NIO", "MSFT", "AAPL", "GOOG", "NFLX", "COIN"]

In [3]:
all_sys_sum = pd.read_csv(all_system_summary)
# all_sys_sum.head()
all_sys_sum

,model,architecture,reflection,n_analyses,n_runs,n_buy,n_hold,n_sell,mean_nmae,mean_penalty_rate,mean_score_one,mean_score,mean_tokens_per_analysis,mean_total_tokens
0,gpt-5-mini,workflow,False,42,1,11,18,13,0.082707,0.0,0.082707,0.082707,78575.714286,78575.714286

In [4]:
one_sys_sum1 = pd.read_csv(one_system_summary)
# one_sys_sum1.head()
one_sys_sum1

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,EBITMargin,3,3,3,1,0.008064,0.005807,0.008064,0.004889,0.0,0.008064,10.0,1,2026-02-25,2026-02-25,NaN
1,GrossMargin,3,3,3,1,0.011889,0.011440,0.011889,0.008151,0.0,0.011889,10.0,1,2026-02-25,2026-02-25,NaN
2,EBIT_TTM,3,3,3,1,0.014235,0.004018,0.014235,0.039966,0.0,0.014235,10.0,1,2026-02-25,2026-02-25,NaN
3,NetRevenue_TTM,3,3,3,1,0.018885,0.002505,0.018885,0.008397,0.0,0.018885,10.0,1,2026-02-25,2026-02-25,NaN
4,NetMargin,3,3,3,1,0.026121,0.021702,0.026121,0.017992,0.0,0.026121,10.0,1,2026-02-25,2026-02-25,NaN
5,NetProfit_TTM,3,3,3,1,0.026324,0.012405,0.026324,0.063742,0.0,0.026324,10.0,1,2026-02-25,2026-02-25,NaN
6,EPS,3,3,3,1,0.042923,0.049884,0.042923,0.067127,0.0,0.042923,10.0,1,2026-02-25,2026-02-25,NaN
7,ShareholdersEquity,3,3,3,1,0.075269,0.075110,0.075269,0.112106,0.0,0.075269,10.0,1,2026-02-25,2026-02-25,NaN
8,EV_EBIT,3,3,3,1,0.086925,0.020442,0.086925,0.217585,0.0,0.086925,10.0,1,2026-02-25,2026-02-25,NaN
9,ROE,3,3,3,1,0.100968,0.072613,0.100968,0.186825,0.0,0.100968,10.0,1,2026-02-25,2026-02-25,NaN
10,GrossDebt_Equity,3,3,3,1,0.111730,0.057190,0.111730,0.412264,0.0,0.111730,10.0,1,2026-02-25,2026-02-25,NaN
11,EV_EBITDA,3,3,3,1,0.119810,0.041481,0.119810,0.224111,0.0,0.119810,10.0,1,2026-02-25,2026-02-25,NaN
12,GrossDebt,3,3,3,1,0.122426,0.096182,0.122426,0.408774,0.0,0.122426,10.0,1,2026-02-25,2026-02-25,NaN
13,CurrentRatio,3,3,3,1,0.122453,0.080006,0.122453,0.094095,0.0,0.122453,10.0,1,2026-02-25,2026-02-25,NaN
14,BVPS,3,3,3,1,0.163470,0.088179,0.163470,0.129608,0.0,0.163470,10.0,1,2026-02-25,2026-02-25,NaN
15,P_E,3,3,3,1,0.164690,0.020674,0.164690,0.215168,0.0,0.164690,10.0,1,2026-02-25,2026-02-25,NaN
16,PriceToSales,3,3,3,1,0.172709,0.209695,0.172709,0.102188,0.0,0.172709,10.0,1,2026-02-25,2026-02-25,NaN
17,P_B,3,3,3,1,0.183558,0.056485,0.183558,0.197376,0.0,0.183558,10.0,1,2026-02-25,2026-02-25,NaN
18,CashAndEquivalents,3,3,3,1,0.599894,0.442164,0.599894,0.603529,0.0,0.599894,10.0,1,2026-02-25,2026-02-25,NaN
19,NetDebt,3,3,3,1,0.980630,1.009952,0.980630,2.315420,0.0,0.980630,10.0,1,2026-02-25,2026-02-25,NaN
20,ROIC,3,3,3,1,1.674215,0.090518,1.674215,0.641208,0.0,1.674215,10.0,1,2026-02-25,2026-02-25,NaN

In [5]:
sys1 = pd.read_csv(each_system_rows)
# sys1.head()
sys1

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,input_tokens,output_tokens,total_tokens,requests,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,AAPL,2026-02-25,0,BVPS,5.998217e+00,5.310000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,41895,7094,48989,2,2.578557e-02,1.296077e-01,minmax_gold,0,5.310000e+00,3.200000e+01
1,AAPL,2026-02-25,0,CashAndEquivalents,4.531700e+10,5.470000e+10,gold,2026-02-25,2026-02-25,USD,...,41895,7094,48989,2,1.650484e-01,1.715356e-01,minmax_gold,0,4.165000e+10,9.850000e+10
2,AAPL,2026-02-25,0,CurrentRatio,9.737447e-01,8.900000e-01,gold,2026-02-25,2026-02-25,multiple,...,41895,7094,48989,2,7.097005e-02,9.409513e-02,minmax_gold,0,8.900000e-01,2.070000e+00
3,AAPL,2026-02-25,0,EBITMargin,3.197080e+01,3.197000e+01,gold,2026-02-25,2026-02-25,percent,...,41895,7094,48989,2,2.951153e-05,2.501603e-05,minmax_gold,0,5.090000e+00,3.219000e+01
4,AAPL,2026-02-25,0,EBIT_TTM,1.330500e+11,1.330500e+11,gold,2026-02-25,2026-02-25,USD,...,41895,7094,48989,2,1.110223e-16,1.146846e-16,minmax_gold,0,4.870000e+09,1.330500e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,TSLA,2026-02-25,0,P_E,3.864815e+02,2.718500e+02,gold,2026-02-25,2026-02-25,multiple,...,53285,5727,59012,2,4.621864e-01,4.216718e-01,minmax_gold,0,2.383000e+01,2.718500e+02
59,TSLA,2026-02-25,0,PriceToSales,1.651078e+01,1.498000e+01,gold,2026-02-25,2026-02-25,multiple,...,53285,5727,59012,2,2.096954e-01,1.021880e-01,minmax_gold,0,7.680000e+00,1.498000e+01
60,TSLA,2026-02-25,0,ROE,4.619112e+00,1.488000e+01,gold,2026-02-25,2026-02-25,percent,...,53285,5727,59012,2,7.261261e-02,6.895758e-01,minmax_gold,0,1.488000e+01,1.561900e+02
61,TSLA,2026-02-25,0,ROIC,6.876663e+00,4.190000e+00,gold,2026-02-25,2026-02-25,percent,...,53285,5727,59012,2,4.832127e-02,6.412083e-01,minmax_gold,0,4.190000e+00,5.979000e+01
62,TSLA,2026-02-25,0,ShareholdersEquity,8.213700e+10,3.817000e+10,gold,2026-02-25,2026-02-25,USD,...,53285,5727,59012,2,1.253514e-01,1.151873e+00,minmax_gold,0,3.817000e+10,3.889200e+11

Dataset

In [6]:
split_2025 = pd.read_csv("/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent/data/processed/splits/test_2025-01-01_to_2026-02-25.csv")
split_2025.head()
mask = (split_2025["date"] == "2026-02-24") & (split_2025["ticker"] == "AAPL")
check = split_2025.loc[mask].iloc[0]
check

date                            2026-02-24
ticker                                AAPL
adj_close                       272.140015
ret_1d                            0.616995
log_ret_1d                        0.022144
Volume                           -0.127226
filed                           2026-01-30
Assets                             0.77603
Liabilities                       1.737268
StockholdersEquity               -0.144499
Revenues                               NaN
NetIncomeLoss                      0.99671
OperatingIncomeLoss               1.155145
EarningsPerShareBasic            -0.028904
CommonStockSharesOutstanding       1.43771
ret_5d                            0.350847
ret_20d                           0.328203
vol_20d                          -0.575568
vol_60d                          -0.992675
target_ret_1d                      0.00768
Name: 285, dtype: object

EU STOCKS

In [7]:
region = "eu"
system = "workflow"
reflection = "false"

all_system_summary_eu = f"{output_path}/results/validation/{region}/table1_{region}_summary.csv"
each_system_rows_eu = f"{output_path}/results/validation/{region}/table2_{region}_rows_{system}_{reflection}.csv"
one_system_summary_eu = f"{output_path}/results/validation/{region}/table2_{region}_summary_{system}_{reflection}.csv"

In [8]:
all_sys_sum_eu = pd.read_csv(all_system_summary_eu)
# all_sys_sum_eu.head()
all_sys_sum_eu

,model,architecture,reflection,n_analyses,n_runs,n_buy,n_hold,n_sell,mean_nmae,mean_penalty_rate,mean_score_one,mean_score,mean_tokens_per_analysis,mean_total_tokens
0,gpt-5-mini,workflow,False,14,1,8,5,1,0.073624,0.0,0.073624,0.073624,16022.571429,16022.571429

In [9]:
one_sys_sum_eu = pd.read_csv(one_system_summary_eu)
# one_sys_sum_eu.head()
one_sys_sum_eu

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,GrossDebt,1,1,1,1,0.003333,0.003333,0.003333,0.003333,0.0,0.003333,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
1,GrossMargin,1,1,1,1,0.005410,0.005410,0.005410,0.005410,0.0,0.005410,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
2,EBITMargin,1,1,1,1,0.027911,0.027911,0.027911,0.027911,0.0,0.027911,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
3,GrossDebt_Equity,1,1,1,1,0.029998,0.029998,0.029998,0.029998,0.0,0.029998,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
4,CurrentRatio,1,1,1,1,0.036797,0.036797,0.036797,0.036797,0.0,0.036797,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
5,NetMargin,1,1,1,1,0.044483,0.044483,0.044483,0.044483,0.0,0.044483,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
6,NetProfit_TTM,1,1,1,1,0.153137,0.153137,0.153137,0.153137,0.0,0.153137,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
7,EBIT_TTM,1,1,1,1,0.173026,0.173026,0.173026,0.173026,0.0,0.173026,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
8,EPS,1,1,1,1,0.173184,0.173184,0.173184,0.173184,0.0,0.173184,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
9,ROIC,1,1,1,1,0.184238,0.184238,0.184238,0.184238,0.0,0.184238,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
10,NetRevenue_TTM,1,1,1,1,0.206843,0.206843,0.206843,0.206843,0.0,0.206843,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
11,PriceToSales,1,1,1,1,0.212259,0.212259,0.212259,0.212259,0.0,0.212259,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
12,EV_EBIT,1,1,1,1,0.229535,0.229535,0.229535,0.229535,0.0,0.229535,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
13,EV_EBITDA,1,1,1,1,0.255399,0.255399,0.255399,0.255399,0.0,0.255399,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
14,P_E,1,1,1,1,0.262715,0.262715,0.262715,0.262715,0.0,0.262715,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
15,CashAndEquivalents,1,1,1,1,1.517739,1.517739,1.517739,1.517739,0.0,1.517739,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
16,NetDebt,1,1,1,1,3.217769,3.217769,3.217769,3.217769,0.0,3.217769,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback

In [10]:
sys_eu = pd.read_csv(each_system_rows_eu)
# sys_eu.head()
sys_eu

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,input_tokens,output_tokens,total_tokens,requests,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,ASML.AS,2026-02-26,0,CashAndEquivalents,1.291600e+10,5.130000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,1.517739,1.517739,ape_fallback_zero_range,0,5.130000e+09,5.130000e+09
1,ASML.AS,2026-02-26,0,CurrentRatio,1.261796e+00,1.310000e+00,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.036797,0.036797,ape_fallback_zero_range,0,1.310000e+00,1.310000e+00
2,ASML.AS,2026-02-26,0,EBITMargin,3.530628e+01,3.632000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.027911,0.027911,ape_fallback_zero_range,0,3.632000e+01,3.632000e+01
3,ASML.AS,2026-02-26,0,EBIT_TTM,1.372440e+10,1.170000e+10,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.173026,0.173026,ape_fallback_zero_range,0,1.170000e+10,1.170000e+10
4,ASML.AS,2026-02-26,0,EPS,2.940000e+01,2.506000e+01,gold,2026-02-26,2026-02-26,USD_per_share,...,10538,6552,17090,2,0.173184,0.173184,ape_fallback_zero_range,0,2.506000e+01,2.506000e+01
5,ASML.AS,2026-02-26,0,EV_EBIT,3.393516e+01,2.760000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.229535,0.229535,ape_fallback_zero_range,0,2.760000e+01,2.760000e+01
6,ASML.AS,2026-02-26,0,EV_EBITDA,3.158585e+01,2.516000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.255399,0.255399,ape_fallback_zero_range,0,2.516000e+01,2.516000e+01
7,ASML.AS,2026-02-26,0,GrossDebt,2.709000e+09,2.700000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.003333,0.003333,ape_fallback_zero_range,0,2.700000e+09,2.700000e+09
8,ASML.AS,2026-02-26,0,GrossDebt_Equity,1.381283e-01,1.424000e-01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.029998,0.029998,ape_fallback_zero_range,0,1.424000e-01,1.424000e-01
9,ASML.AS,2026-02-26,0,GrossMargin,5.215629e+01,5.244000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.005410,0.005410,ape_fallback_zero_range,0,5.244000e+01,5.244000e+01
10,ASML.AS,2026-02-26,0,NetDebt,-1.020700e+10,-2.420000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,3.217769,3.217769,ape_fallback_zero_range,0,-2.420000e+09,-2.420000e+09
11,ASML.AS,2026-02-26,0,NetMargin,2.921970e+01,3.058000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.044483,0.044483,ape_fallback_zero_range,0,3.058000e+01,3.058000e+01
12,ASML.AS,2026-02-26,0,NetProfit_TTM,1.135840e+10,9.850000e+09,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.153137,0.153137,ape_fallback_zero_range,0,9.850000e+09,9.850000e+09
13,ASML.AS,2026-02-26,0,NetRevenue_TTM,3.887240e+10,3.221000e+10,gold,2026-02-26,2026-02-26,USD,...,10538,6552,17090,2,0.206843,0.206843,ape_fallback_zero_range,0,3.221000e+10,3.221000e+10
14,ASML.AS,2026-02-26,0,P_E,4.170748e+01,3.303000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.262715,0.262715,ape_fallback_zero_range,0,3.303000e+01,3.303000e+01
15,ASML.AS,2026-02-26,0,PriceToSales,1.224382e+01,1.010000e+01,gold,2026-02-26,2026-02-26,multiple,...,10538,6552,17090,2,0.212259,0.212259,ape_fallback_zero_range,0,1.010000e+01,1.010000e+01
16,ASML.AS,2026-02-26,0,ROIC,3.648088e+01,4.472000e+01,gold,2026-02-26,2026-02-26,percent,...,10538,6552,17090,2,0.184238,0.184238,ape_fallback_zero_range,0,4.472000e+01,4.472000e+01

In [11]:
# split_2025_eu = pd.read_csv("/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent/data_eu/processed/splits/test_2025-01-01_to_2026-02-26.csv")
# # split_2025_eu.head()
# mask_eu = (split_2025["date"] == "2026-02-24") & (split_2025["ticker"] == "ASML.AS")
# check_eu = split_2025.loc[mask].iloc[0]
# check_eu