In [5]:
# At (Pdb) prompt:
# n next line
# s step into
# c continue
# p args / pp requested_tickers inspect vars
# l show code
# q quit
# Workflow mode
# %run -d -b 113 -b 118 -b 184 -b 195 run_one_ticker.py -- --ticker TSLA --mode workflow --model gpt-5-mini --n-times 1 --max-turns 30
# Agent mode (with MCP)
# %run -d -b 113 -b 118 -b 177 -b 186 -b 195 run_one_ticker.py -- --ticker TSLA --mode agent --model gpt-5-mini --mcp --n-times 1 --max-turns 30

In [13]:
import pandas as pd

TICKERS_EU = [ "KRZ.IR", "A5G.IR", "BIRG.IR", "ASML.AS", "SAP.DE", "MC.PA", "NOVO-B.CO", "SIE.DE", "OR.PA", "NESN.SW",]
TICKERS = ["TSLA", "AMZN", "NIO", "MSFT", "AAPL", "GOOG", "NFLX", "COIN"]
output_path="/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent"

region = "us"
system = "workflow"
reflection = "false"

all_system_summary = f"{output_path}/results/validation/{region}/table1_{region}_summary.csv"
each_system_rows = f"{output_path}/results/validation/{region}/table2_{region}_rows_{system}_{reflection}.csv"
one_system_summary = f"{output_path}/results/validation/{region}/table2_{region}_summary_{system}_{reflection}.csv"

US STOCKS ["TSLA", "AMZN", "NIO", "MSFT", "AAPL", "GOOG", "NFLX", "COIN"]

In [14]:
all_sys_sum = pd.read_csv(all_system_summary)
all_sys_sum.head()

,model,architecture,reflection,n_analyses,n_runs,n_buy,n_hold,n_sell,mean_nmae,mean_penalty_rate,mean_score_one,mean_score,mean_tokens_per_analysis,mean_total_tokens
0,gpt-5-mini,workflow,False,14,1,2,10,2,0.100145,0.0,0.100145,0.100145,56040.857143,56040.857143

In [15]:
one_sys_sum = pd.read_csv(one_system_summary)
one_sys_sum.head()

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,EPS,1,1,1,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,10.0,1,2026-02-25,2026-02-25,constant_gold_range_fallback
1,NetProfit_TTM,1,1,1,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,10.0,1,2026-02-25,2026-02-25,constant_gold_range_fallback
2,EBIT_TTM,1,1,1,1,1.146846e-16,1.146846e-16,1.146846e-16,1.146846e-16,0.0,1.146846e-16,10.0,1,2026-02-25,2026-02-25,constant_gold_range_fallback
3,NetRevenue_TTM,1,1,1,1,2.402922e-06,2.402922e-06,2.402922e-06,2.402922e-06,0.0,2.402922e-06,10.0,1,2026-02-25,2026-02-25,constant_gold_range_fallback
4,EBITMargin,1,1,1,1,2.501603e-05,2.501603e-05,2.501603e-05,2.501603e-05,0.0,2.501603e-05,10.0,1,2026-02-25,2026-02-25,constant_gold_range_fallback

In [16]:
sys= pd.read_csv(each_system_rows)
sys.head()

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,input_tokens,output_tokens,total_tokens,requests,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,AAPL,2026-02-25,0,BVPS,5.998217e+00,5.310000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,41895,7094,48989,2,1.296077e-01,1.296077e-01,ape_fallback_zero_range,0,5.310000e+00,5.310000e+00
1,AAPL,2026-02-25,0,CashAndEquivalents,4.531700e+10,5.470000e+10,gold,2026-02-25,2026-02-25,USD,...,41895,7094,48989,2,1.715356e-01,1.715356e-01,ape_fallback_zero_range,0,5.470000e+10,5.470000e+10
2,AAPL,2026-02-25,0,CurrentRatio,9.737447e-01,8.900000e-01,gold,2026-02-25,2026-02-25,multiple,...,41895,7094,48989,2,9.409513e-02,9.409513e-02,ape_fallback_zero_range,0,8.900000e-01,8.900000e-01
3,AAPL,2026-02-25,0,EBITMargin,3.197080e+01,3.197000e+01,gold,2026-02-25,2026-02-25,percent,...,41895,7094,48989,2,2.501603e-05,2.501603e-05,ape_fallback_zero_range,0,3.197000e+01,3.197000e+01
4,AAPL,2026-02-25,0,EBIT_TTM,1.330500e+11,1.330500e+11,gold,2026-02-25,2026-02-25,USD,...,41895,7094,48989,2,1.146846e-16,1.146846e-16,ape_fallback_zero_range,0,1.330500e+11,1.330500e+11

Dataset

In [17]:
split_2025 = pd.read_csv("/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent/data/processed/splits/test_2025-01-01_to_2026-02-25.csv")
split_2025.head()
mask = (split_2025["date"] == "2026-02-24") & (split_2025["ticker"] == "AAPL")
check = split_2025.loc[mask].iloc[0]
check

date                            2026-02-24
ticker                                AAPL
adj_close                       272.140015
ret_1d                            0.616995
log_ret_1d                        0.022144
Volume                           -0.127226
filed                           2026-01-30
Assets                             0.77603
Liabilities                       1.737268
StockholdersEquity               -0.144499
Revenues                               NaN
NetIncomeLoss                      0.99671
OperatingIncomeLoss               1.155145
EarningsPerShareBasic            -0.028904
CommonStockSharesOutstanding       1.43771
ret_5d                            0.350847
ret_20d                           0.328203
vol_20d                          -0.575568
vol_60d                          -0.992675
target_ret_1d                      0.00768
Name: 285, dtype: object

EU STOCKS

In [18]:
region = "eu"
system = "workflow"
reflection = "false"

all_system_summary_eu = f"{output_path}/results/validation/{region}/table1_{region}_summary.csv"
each_system_rows_eu = f"{output_path}/results/validation/{region}/table2_{region}_rows_{system}_{reflection}.csv"
one_system_summary_eu = f"{output_path}/results/validation/{region}/table2_{region}_summary_{system}_{reflection}.csv"

In [19]:
all_sys_sum_eu = pd.read_csv(all_system_summary_eu)
all_sys_sum_eu.head()

,model,architecture,reflection,n_analyses,n_runs,n_buy,n_hold,n_sell,mean_nmae,mean_penalty_rate,mean_score_one,mean_score,mean_tokens_per_analysis,mean_total_tokens
0,gpt-5-mini,workflow,False,14,1,7,5,2,0.026112,0.0,0.026112,0.026112,12609.357143,12609.357143

In [20]:
one_sys_sum_eu = pd.read_csv(one_system_summary_eu)
one_sys_sum_eu.head()

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,EBITMargin,1,1,1,1,0.027911,0.027911,0.027911,0.027911,0.0,0.027911,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
1,NetMargin,1,1,1,1,0.044483,0.044483,0.044483,0.044483,0.0,0.044483,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
2,EPS,1,1,1,1,0.706704,0.706704,0.706704,0.706704,0.0,0.706704,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
3,CashAndEquivalents,1,1,1,1,1.000000,1.000000,1.000000,1.000000,1.0,11.000000,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback
4,CurrentRatio,1,1,1,1,1.000000,1.000000,1.000000,1.000000,1.0,11.000000,10.0,1,2026-02-26,2026-02-26,constant_gold_range_fallback

In [21]:
sys_eu = pd.read_csv(each_system_rows_eu)
sys_eu.head()

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,input_tokens,output_tokens,total_tokens,requests,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,ASML.AS,2026-02-26,0,CashAndEquivalents,0.000000,5.130000e+09,gold,2026-02-26,2026-02-26,USD,...,7208,3465,10673,2,1.000000,1.000000,ape_fallback_zero_range,0,5.130000e+09,5.130000e+09
1,ASML.AS,2026-02-26,0,CurrentRatio,0.000000,1.310000e+00,gold,2026-02-26,2026-02-26,multiple,...,7208,3465,10673,2,1.000000,1.000000,ape_fallback_zero_range,0,1.310000e+00,1.310000e+00
2,ASML.AS,2026-02-26,0,EBITMargin,35.306284,3.632000e+01,gold,2026-02-26,2026-02-26,percent,...,7208,3465,10673,2,0.027911,0.027911,ape_fallback_zero_range,0,3.632000e+01,3.632000e+01
3,ASML.AS,2026-02-26,0,EBIT_TTM,0.000000,1.170000e+10,gold,2026-02-26,2026-02-26,USD,...,7208,3465,10673,2,1.000000,1.000000,ape_fallback_zero_range,0,1.170000e+10,1.170000e+10
4,ASML.AS,2026-02-26,0,EPS,7.350000,2.506000e+01,gold,2026-02-26,2026-02-26,USD_per_share,...,7208,3465,10673,2,0.706704,0.706704,ape_fallback_zero_range,0,2.506000e+01,2.506000e+01